Post authentication hook
rtCamp/login-with-google pull request #91
Opened 2021-08-31 16:14 UTC by ankitrox

Add the hook once the user has been authenticated successfully.

2021-11-15 21:24 UTC, renzit commented
Would be nice to have! is there any workaround to redirect users to other than wp-admin?

2022-07-25 12:38 UTC, abhishekfdd commented
Verified. 
Closes issue #89

2022-07-25 13:23 UTC, chandrapatel requested changes

2022-07-25 13:23 UTC, chandrapatel commented on src/Modules/Login.php
> +				 * @since 1.2.2
This is the current version and this new action going to release in newer version. So maybe it's `1.2.3` or `1.3.0`?

2022-07-25 13:24 UTC, chandrapatel commented on src/Modules/Login.php
> +				 * @since 1.2.2
@abhishekfdd

2022-07-25 16:04 UTC, chandrapatel requested changes

2022-07-25 16:04 UTC, chandrapatel commented on src/Modules/Login.php
> +				 * @since 1.2.3
Ideally `@since` should be above `@param`. Also add blank line after `@since`. I missed this in last review. Apologies.

2022-07-26 12:05 UTC, chandrapatel approved these changes

2022-07-26 12:48 UTC, merged